services:
  fluidsender:
    image: ghcr.io/fluidsender/fluidsender-ui:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      NODE_ENV: production
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "3000"
